### ISSUE TITLE
[Title renders included] Make menu logo show their codes.

### ISSUE THREAD

**Issue by BlebTheWobbly** [SkyEye-FAST/key_language_pack#1]
1.20+ Title image:
![image](https://github.com/SkyEye-FAST/key_language_pack/assets/113015055/ddad7fff-c9f3-48fc-85f3-dfb401c86aab)
1.19- Title image:
![image](https://github.com/SkyEye-FAST/key_language_pack/assets/113015055/9430d122-029d-4695-9e9f-d51f31660e31)
(Yes. Ugly look but that is the format.)
Mojang studios replacement image:
![image](https://github.com/SkyEye-FAST/key_language_pack/assets/113015055/646b4223-3291-480e-ad01-0137a0219f49)

**Comment by SkyEye-FAST** [comment]
The key in the images doesn't exist in the language files. I'm afraid that changing the logo to these images will cause ambiguity. 

After all, this resource pack is for technical use, and it would be bad if someone thinks that the key does exist in the language files. Perhaps other options could be considered?
